
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ../../../target:/usr/local/tomcat/webapps
      - ../../../lib/mysql-connector-j-9.0.0.jar:/usr/local/tomcat/lib/mysql-connector-j-9.0.0.jar
      - $HOME/config.properties:/root/config.properties

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
